[package]
name = "gputeer-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "gputeer"
path = "src/main.rs"

[dependencies]
gputeer-protocol = { path = "../protocol" }
gputeer-crypto = { path = "../crypto" }
gputeer-checkpoint = { path = "../checkpoint" }
gputeer-runtime-policy = { path = "../runtime-policy" }
gputeer-coordinator = { path = "../coordinator" }
gputeer-agent = { path = "../agent" }
gputeer-runtime-nvml = { path = "../runtime-nvml" }
gputeer-scheduler = { path = "../scheduler" }
prost.workspace = true
tempfile.workspace = true
serde = { workspace = true }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
