[package]
name = "gputeer-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
thiserror.workspace = true
prost.workspace = true
ed25519-dalek.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
rand_core.workspace = true
serde_json.workspace = true
